# Site
name: "soragui"
title: "soragui"
description: ""
logo: 'assets/images/avator.ico'
favicon: 'assets/images/avator.ico'
baseurl: ''
google_analytics: 'G-NHCB0068DQ'
disqus: 'soragui'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: soragui
    display_name: soragui
    gravatar: b6e8f7083371a207ce81a546af52867b
    email: ziwo520@gmail.com
    web: https://soragui.com
    twitter: https://twitter.com/ziwo520
    description: "编程-学习-思考"

# Categories
cates:
  daily:
    name: Week Notes
    permalink: /catedaily
    image: assets/images/weeknote.jpg
    description: 每周学习收获总结
  flutter:
    name: Flutter
    permalink: /cateflutter
    image: assets/images/flutter.png
    description: Flutter学习总结
  css:
    name: CSS 的故事
    permalink: /catecss
    image: assets/images/csscover.png
    description: 记录 CSS 相关知识级学习笔记
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
